# Configuration file for Travis CI

language: cpp

# Only build pushes to the master branch and tags. This avoids the double
# builds than happen when working on a branch instead of a fork.
branches:
  only:
    - master
    # Regex to build tagged commits with version numbers
    - /\d+\.\d+(\.\d+)?(\S*)?$/

jobs:
  include:
    - os: linux
      dist: bionic
      sudo: required
      env: PATH="/opt/qt514/bin:$PATH"
      before_install:
      - sudo add-apt-repository ppa:beineri/opt-qt-5.14.0-bionic -y
      - sudo apt-get update
      - sudo apt-get install qt514-meta-minimal libglu1-mesa-dev
    - os: osx
      osx_image: xcode11.3
      env: PATH="/usr/local/opt/qt/bin:$PATH"
      before_install:
      # Travis CI already has qt 5.13 installed
      - brew reinstall qt

script:
  # Check qmake --version
  - qmake --version
  # Building
  - make build

after_success:
  # Packaging
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make macos_package; fi

deploy:
  provider: script
  skip_cleanup: true
  script: if [ "$TRAVIS_OS_NAME" = "osx" ]; then curl -T build/GMT-GUI.app.zip -u $FTP_USER:$FTP_PASSWORD ftp://home.ustc.edu.cn/public_html/; fi
  on:
    branch: master
